### PR TITLE
[91] Linux Incorrect modelcard-schema Path

### LINKED ISSUE #91: Linux Incorrect modelcard-schema Path
### Bug description

After rebasing the deep learning effect to Audacity 3.2 the file path given by `FileNames::BaseDir()` method has changed. This is the result in a change in the underlying behavior of the `wxStandardPaths::Get().GetPluginsDir()` method. 

### Steps to reproduce

1. Build the audacity `rebase-3.2` branch from source
2. Install the app
3. Launch the application
4. Record audio
5. Select audio
6. Apply Effect>Deep Learning Effect

### Expected behavior

The deep learning effect dialog box should appear

### Actual behavior

An assertion is failed with error message: "/home/runner/work/conan-recipes/conan-recipes/.conan/data/wxwidgets/3.1.3.3-audacity/_/_/build/56857e0e62a84915b281eee5e4c3d81bc7426813/source_subfolder/src/common/file.cpp(475): assert "IsOpened()" failed in Length()."

### Audacity Version

other

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aldo-aguilar**
Resolves: [Linux Incorrect modelcard-schema Path #91 ](https://github.com/audacitorch/audacity/issues/91)

updated cmake since it is no longer needed to set the modules dst path based on platform.

changed linux filepath for model-schema `modules/mod-deep-learning/DeepModel.cpp`, this is platform dependent for now as I cannot test on Mac or on Windows at the moment. 

removed unnecessary logging in `modules/mod-deep-learning/DeepModelManager.cpp`

### CODE REVIEW

File: modules/mod-deep-learning/DeepModel.cpp [hunk 1]
```diff
@@ -28,7 +28,11 @@ FilePath DeepModel::DLModelsDir()
 
 FilePath DeepModel::BuiltInModulesDir()
 {
-   return FileNames::MkDir( wxFileName( FileNames::BaseDir(), wxT("deeplearning-models") ).GetFullPath() );
+   #if defined(__WXOSX__) || defined(__WXMSW__)
+      return FileNames::MkDir( wxFileName( FileNames::BaseDir(), wxT("deeplearning-models") ).GetFullPath() );
+   #else
+      return FileNames::MkDir( wxFileName( FileNames::ResourcesDir(), wxT("deeplearning-models") ).GetFullPath() );
+   #endif
```
Comment (hugofloresgarcia) [inline modules/mod-deep-learning/DeepModel.cpp:35]: is there a chance we could just use `ResourcesDir()` for all platforms?

**Review by hugofloresgarcia — COMMENTED** [review]
see the comment ab using the same resource dir for builtin models regardless of platform. otherwise lgtm!

File: modules/mod-deep-learning/DeepModel.cpp (hunk 1 above)
Comment (aldo-aguilar) [reply modules/mod-deep-learning/DeepModel.cpp:35]: I think this would be ideal, but I'm still working on the windows build and can't test mac builds yet. 

we can either wait until it's tested on all platforms, or I can create issues to check this support when we have the builds working

merging now helps prevent a hacky solution to this problem on linux

Comment (hugofloresgarcia) [reply modules/mod-deep-learning/DeepModel.cpp:35]: yeah, sounds good. merge away! let's open a new issue for using the same resource dir to not forget ab it.

**Review by hugofloresgarcia — APPROVED** [review]
