### PR TITLE
[90] implimented a simple solution to bug for issue 90

### LINKED ISSUE #90: Crash after waveform-to-labels error message
**Describe the bug**
After attempting to run the waveform-to-labels model `aguilara42/audacity-Wav2Vec2-Base`, an assertion error is thrown. After closing the error message, audacity crashes.

ASSERT INFO:
```
~/Desktop/audacity/modules/mod-deep-learning/DeepLearningAnalyzer.cpp(193): assert "output.dim() == 1" failed in TensorToLabelTrack().
```

BACKTRACE:
```
[1] DeepLearningAnalyzer::TensorToLabelTrack(at::Tensor, Effect::AddedAnalysisTrack&, double, double, at::Tensor, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
[2] DeepLearningAnalyzer::ProcessOne(WaveTrack*, double, double)
[3] DeepLearningEffectBase::Process()
[4] Effect::DoEffect(double, TrackList*, WaveTrackFactory*, NotifyingSelectedRegion&, unsigned int, wxWindow*, std::function<wxDialog* (wxWindow&, EffectHostInterface&, EffectUIClientInterface&)> const&)
[5] EffectUI::DoEffect(wxString const&, CommandContext const&, unsigned int)
[6] PluginActions::Handler::OnEffect(CommandContext const&)
[7] CommandManager::HandleCommandEntry(AudacityProject&, CommandListEntry const*, std::bitset<64ul>, bool, wxEvent const*, CommandContext const*)
[8] CommandManager::HandleMenuID(AudacityProject&, int, std::bitset<64ul>, bool)
[9] ProjectWindow::OnMenu(wxCommandEvent&)
[10] wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
[11] wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
[12] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[13] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[14] wxEvtHandler::TryHereOnly(wxEvent&)
[15] wxEvtHandler::TryBeforeAndHere(wxEvent&)
[16] wxEvtHandler::ProcessEvent(wxEvent&)
[17] wxEvtHandler::DoTryChain(wxEvent&)
[18] wxEvtHandler::ProcessEventLocally(wxEvent&)
[19] wxEvtHandler::ProcessEvent(wxEvent&)
[20] wxWindowBase::TryAfter(wxEvent&)
[21] wxEvtHandler::ProcessEvent(wxEvent&)
[22] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[23] wxWindowBase::HandleWindowEvent(wxEvent&) const
[24] wxMenuBase::DoProcessEvent(wxMenuBase*, wxEvent&, wxWindow*)
[25] wxMenuBase::SendEvent(int, int)
[26] g_closure_invoke
[27] g_signal_emit_valist
[28] g_signal_emit
[29] gtk_widget_activate
[30] gtk_menu_shell_activate_item
[31] g_closure_invoke
[32] g_signal_emit_valist
[33] g_signal_emit
[34] gtk_propagate_event
[35] gtk_main_do_event
[36] g_main_context_dispatch
[37] g_main_loop_run
[38] gtk_main
[39] wxGUIEventLoop::DoRun()
[40] wxEventLoopBase::Run()
[41] wxAppConsoleBase::MainLoop()
[42] wxAppConsoleBase::OnRun()
[43] wxAppBase::OnRun()
[44] AudacityApp::OnRun()
[45] wxEntry(int&, wchar_t**)
[46] wxEntry(int&, char**)
[47] main
[48] __libc_start_main
[49] _start
```

The crash seems to happen intermittently.

**To Reproduce**
1. In the "Deep Learning Analyzer" window, click "Add From Hugging Face"
2. Type "aguilara42/openl3-labeler-w-timestamps" and click "OK"
3. Find the model in the list and click "Install"
4. After the model is installed, select it and click "OK"
5. An error message should pop up - click "Continue"

**Expected behavior**
Close the error message with no crash.

**Additional information:**
 - OS: Ubuntu 18.04
 - Version v3.2.0-alpha

### PR DESCRIPTION
**Pull request by aldo-aguilar**
Resolves: [issue 90](https://github.com/audacitorch/audacity/issues/90)

this change will resolve issue 90, instead of using `wxASSERT()` to check if the labeler has output of size 1, we directly compare in an if statement and throw a `ModelException` if the output  dim is not equal to 1. 

this solution prevents the app from crashing when there is a miss-match on the output dim, and gives the user information about the crash. 

it appears that `wxASSERT()` is for catching bugs inside of the debug build, and would not resolve this issue in release builds. 
[source](https://docs.wxwidgets.org/3.0/group__group__funcmacro__debug.html#ga204cc264ee560b67e6c6467ba8ffee5f)

### CODE REVIEW

File: modules/mod-deep-learning/DeepLearningAnalyzer.cpp [hunk 1]
```diff
@@ -196,7 +196,10 @@ void DeepLearningAnalyzer::TensorToLabelTrack
    timestamps += tStart;
 
    // check that the output is one dimensional
-   wxASSERT(output.dim() == 1);
+   if (output.dim() != 1)
+      throw ModelException {
+         XO("Labeler model output is not a single track."), ""
```
Comment (hugofloresgarcia) [inline modules/mod-deep-learning/DeepLearningAnalyzer.cpp]: I feel like the details of this exception are for model developers, since it's likely due to model developer error. 

It would be more informational to say `Model Error: The tensor output by the labeler model has more than one dimension` or something along the lines of that.

**Review by hugofloresgarcia — CHANGES_REQUESTED** [review]

File: modules/mod-deep-learning/DeepLearningAnalyzer.cpp (hunk 1 above)
Comment (aldo-aguilar) [reply modules/mod-deep-learning/DeepLearningAnalyzer.cpp]: I changed it to the string "Model Error: The tensor output by the labeler model is not one dimension." just because it may be that the output is of dim 0 (i'm not sure why this would happen but the code doesn't distinguish between > 1 or 0)

**Review by xribene — APPROVED** [review]
